/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class indi_sword_util_basic_jni_HelloJNI */

#ifndef _Included_indi_sword_util_basic_jni_HelloJNI
#define _Included_indi_sword_util_basic_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     indi_sword_util_basic_jni_HelloJNI
 * Method:    sayHi
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_indi_sword_util_basic_jni_HelloJNI_sayHi
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
